blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path ('', render_posts, name='post'),
    path ("<int:post_id>", post_detail, name="post_detail"),
]

django_porfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from porfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images/")
    date = models.DateField(datetime.date.today)

porfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=260)
    image = ImageField(upload_to="porfolio/images/")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post





def render_posts(request):
    posts = Post.objects.all()
    return render (request, 'post.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

porfolio/views.py
from django.shortcuts import render
from .models import Project
def home(request):
    projects = Project.objects.all()
    
    
    return render(request, 'home.html', {'projects': projects})    

blog/templates/post.html
{% extends 'layout.html' %}
{% block content %}
    <h1>Post</h1>
    {% for post in posts %}


    <div class="p-3">
        <div class="card card-body bg-black">
            <div class="row">
                <div class="col-3">
                    <img src="{{ post.image.url }}"
                         class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}"
                         alt="">
                    <div class="col-9">
                        <h2>{{ post.title }}</h2>
                        <p>
                            {{ post.description|striptags|truncatechars:100 }}
                        </p>
                        <p>
                            {{ post.date|date:'M d Y'|upper }}
                        </p>

                        <a href="{% url 'blog:post_detail' post.id %}"class="btn btn-primary">{{ post.title }}</a>
                    
                    </div>
                </div>
            
            </div>
        </div>
    </div>


    {% endfor %}
{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
    <div class="text-center">
        <h2>{{ post.title }}</h2>
        <h3 class="my-2 h5 text-muted">{{ post.date|date:'F j Y' }}</h3>
        <img src="{{ post.image.url }}"
             class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}"
             alt="">
        <div class="my-4">
            <p>
                {{ post.description|safe }}
            </p>
        </div>
    </div>
{% endblock %}

porfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    {% load static %}
    <header class="row bg-black">
        <div class="col-md-4">
            <img src="{% static 'portfolio/simsom.jpg' %}"
                 class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}"
                 alt="">
        </div>
        <div class="col-md-8 my-auto">
            <h1>
                I am <strong>Pianicsong</strong>
            </h1>
            <h3>I am a Python FullStack Developer</h3>
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis quod adipisci vitae cupiditate fugit nihil, unde amet iusto iure excepturi eos error ea dolorum explicabo repudiandae praesentium aut, expedita ab reprehenderit veritatis tenetur alias fuga? Corrupti doloribus quaerat ipsum facilis, cum, nulla sed excepturi, fugiat eligendi sapiente eveniet voluptatem voluptatum explicabo dolore ut? Iure nesciunt, eveniet illum omnis commodi necessitatibus voluptates qui possimus rerum mollitia debitis sequi iusto, voluptatem, in cumque laborum provident odio ipsam quaerat. Facilis illum numquam fugit, aspernatur non labore commodi eum nesciunt deleniti, officia optio earum voluptas saepe eveniet unde aperiam laboriosam minus alias architecto tempore.
            </p>
            <a href="{% static 'portfolio/quieres.pdf' %}"
               class="btn btn-primary btn-lg rounded-0 my-3"
               target="_blank">Dowload</a>
        </div>
    </header>
    <div class="row my-4 text-center">
        <h3>My Project</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus incidunt molestias voluptatum vitae sapiente excepturi reprehenderit nulla commodi expedita, animi id laudantium dolor deserunt assumenda hic eveniet amet blanditiis rem ut quibusdam explicabo provident. Repellat nihil veritatis fugiat commodi laborum quidem quas nisi eaque, amet cupiditate. Repellat aspernatur facere modi!
        </p>
        {% for project in projects %}
            <div class="col-md-4 p-4">
                <div class="card bg-black card-project">
                    <img src="{{ project.image.url }}"
                         class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}"
                         alt=""
                         class="card-img-top">
                    <div class="card-body">
                        <h2>{{ project.title }}</h2>
                        <p>
                            {{ project.description }}
                        </p>
                        <a href="{{ project.url }}"
                           class="btn btn-ligth rounder-0 btn-sm"
                           target="_blank">{{ project.url }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endblock %}
</div>

porfolio/templates/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cartelera Web</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href={% static 'main.css' %}
</head>
<body class="text-light">
    {% include 'parcial/navbar.html' %}

    <div class="container p-4">
    {% block content %}
    {% endblock %}
    
     
</body>
</html>

porfolio/templates/parcial/navbar.html
{% load static %}




<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-ital" href="/">FL</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{%  static 'portfolio/quieres.pdf' %}" 
            target="_blank"
            >Download CV
            </a>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>